# docker build -t multi-deploy:base -f Dockerfile.base .
FROM        python:3.6.5-slim

RUN         apt-get -y update --fix-missing
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install nginx supervisor

COPY        ./requirements.txt      /srv/requirements.txt

# pipenv lock --requirements > requirements.txt 으로 사전에 생성해놓
RUN         pip install -r /srv/requirements.txt

